### ISSUE TITLE
Cannot refresh sprint

### ISSUE THREAD

**Issue by frarees** [devtyr/trello-burndown#22] opened 2013-10-01 09:39 UTC
I get a broken link when I access to `http://localhost:8008/refresh?sprint=<MYSPRINT>`. 

Node console says: 

```
[STATUS] RestClient request send, URL: https://api.trello.com/1/boards/522daeb3f207f151530062fc/lists
[STATUS] RestClient request send, Method: GET
Error: [object Object]
Error: Error: [object Object]
```

I've set the `settings.json` with dev key and never-expire token.

**Comment by frarees** [comment] 2013-10-01 09:42
Note that the trello board is under an organization.

**Comment by frarees** [comment] 2013-10-01 09:56
Also, I've tried with a private board I've made, and after refreshing it throws an error: 

```
TypeError: Cannot read property 'length' of null
    at CardStatistics.generate (/Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/lib/cardstatistics.js:36:14)
    at /Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/lib/helper.js:90:15
    at /Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/lib/cardreceiver.js:64:9
    at /Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/node_modules/trello_ex/main.js:20:13
    at Request._callback (/Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/node_modules/trello_ex/node_modules/rest-client/lib/index.js:67:9)
    at Request.self.callback (/Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/node_modules/trello_ex/node_modules/rest-client/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/node_modules/trello_ex/node_modules/rest-client/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/frarees/Documents/trello-burndown/node_modules/trello-burndown/node_modules/trello_ex/node_modules/rest-client/node_modules/request/request.js:824:12)
```

**Comment by devtyr** [comment] 2013-10-01 19:21
It seems that you have an old version running. Try the latest files from this repository.

Having the Trello board under an organization is no problem.

**Comment by devtyr** [comment] 2013-10-15 16:20
Closed this issue because of no new interaction.

**Closed as completed by devtyr** 2013-10-15 16:20 UTC

**Comment by FuriousCoder74** [comment] 2014-02-01 22:05
Having this problem now with v0.9.2 via NPM Install.  Same output as above.

**Comment by devtyr** [comment] 2014-02-25 19:37
May it be caused by the configuration?

**Comment by diramos1** [comment] 2016-03-31 20:27
I'm having the same problem, someone found the reason?

**Comment by derekhardwick** [comment] 2017-06-19 14:47
Same problem here.  Both on latest in master and 0.9.4

> [STATUS] RestClient request send, URL: https://api.trello.com/1/members/me/boards
[STATUS] RestClient request send, Method: GET
Error: [object Object]
    at /Users/derek/Working/trello-burndown-0.9.4/node_modules/trello_ex/main.js:22:22
    at Request._callback (/Users/derek/Working/trello-burndown-0.9.4/node_modules/rest-client/lib/index.js:67:9)
    at Request.self.callback (/Users/derek/Working/trello-burndown-0.9.4/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/derek/Working/trello-burndown-0.9.4/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/derek/Working/trello-burndown-0.9.4/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
